"""Compact simulation manifests, cleanup, FITS loading, and PyTorch datasets."""

from .cleanup import CleanupEntry, CleanupReport, cleanup_simulation_sample
from .dataset import FitsSimulationDataset, simulation_collate
from .fits import FitsPlane, load_fits_plane, validate_fits_products, validate_fits_triplet
from .finalize import FinalizedSample, finalize_simulation_sample
from .loader import make_simulation_dataloader
from .partitions import (
    ALL_IDS,
    PARTITION_IDS,
    PARTITION_NAMES,
    TEST_IDS,
    TRAIN_IDS,
    VAL_IDS,
    get_partition_ids,
    normalize_partition,
    partition_for_sample,
    source_dataset_id,
)
from .schema import (
    CHANNEL_ORDER,
    CORRUPTION_SCHEMA_VERSION,
    DATASET_SCHEMA_VERSION,
    SAMPLE_SCHEMA_VERSION,
    SUPPORTED_QA_SCHEMAS,
    SUPPORTED_CORRUPTION_SCHEMAS,
    SUPPORTED_SIMULATION_SCHEMAS,
    CorruptionReference,
    DatasetManifest,
    SampleManifest,
    add_sample_to_dataset,
    atomic_write_json,
    build_integrity,
    create_sample_manifest,
    load_dataset_manifest,
    load_sample_manifest,
    referenced_files,
    resolve_reference,
    sha256_file,
    write_sample_manifest,
    write_dataset_manifest,
)

__all__ = [
    "CHANNEL_ORDER",
    "CORRUPTION_SCHEMA_VERSION",
    "DATASET_SCHEMA_VERSION",
    "SAMPLE_SCHEMA_VERSION",
    "SUPPORTED_QA_SCHEMAS",
    "SUPPORTED_CORRUPTION_SCHEMAS",
    "SUPPORTED_SIMULATION_SCHEMAS",
    "ALL_IDS",
    "CleanupEntry",
    "CleanupReport",
    "CorruptionReference",
    "DatasetManifest",
    "FitsPlane",
    "FitsSimulationDataset",
    "FinalizedSample",
    "SampleManifest",
    "PARTITION_IDS",
    "PARTITION_NAMES",
    "TEST_IDS",
    "TRAIN_IDS",
    "VAL_IDS",
    "add_sample_to_dataset",
    "atomic_write_json",
    "build_integrity",
    "create_sample_manifest",
    "finalize_simulation_sample",
    "get_partition_ids",
    "cleanup_simulation_sample",
    "load_dataset_manifest",
    "load_fits_plane",
    "load_sample_manifest",
    "make_simulation_dataloader",
    "normalize_partition",
    "partition_for_sample",
    "referenced_files",
    "resolve_reference",
    "sha256_file",
    "simulation_collate",
    "source_dataset_id",
    "validate_fits_products",
    "validate_fits_triplet",
    "write_sample_manifest",
    "write_dataset_manifest",
]
