# this script is all of the individual CASA commands for the 3c391 tutorial
#
# start casa: casa-pipe -r 6.5.4-9-pipeline-2023.1.0.124
#
# it is assumed that the ms has been downloaded into a dedicated directory 
# this has been tested in CASA 6.5.4

# tclean commands are not interactive. 
# all figures are saved as png files
#
# printing listobs - this will print out to the logger
obs_dict = listobs(vis='3c391_ctm_mosaic_10s_spw0.ms')
#
# plot antennas
plotants(vis='3c391_ctm_mosaic_10s_spw0.ms',figfile='plotants_3c391_antenna_layout.png')
clearstat() # This removes the table lock generated by plotants in script mode
#
# editing data
#
# flagging scan
flagdata(vis='3c391_ctm_mosaic_10s_spw0.ms', flagbackup=True, mode='manual', scan='1')
#
# flagging bad antennas
flagdata(vis='3c391_ctm_mosaic_10s_spw0.ms', flagbackup=True, mode='manual', antenna='ea13,ea15')
#
# quack flagging
flagdata(vis='3c391_ctm_mosaic_10s_spw0.ms', mode='quack', quackinterval=10.0, quackmode='beg')
#
clearstat() # This removes any existing table locks generated by flagdata
#
plotms(vis='3c391_ctm_mosaic_10s_spw0.ms', selectdata=True, correlation='RR,LL', averagedata=True, avgchannel='64', coloraxis='field',plotfile='colorbyfield.png')
#
#
# figure 3A plot amp vs uvdist
plotms(vis='3c391_ctm_mosaic_10s_spw0.ms',field='0',selectdata=True,correlation='RR,LL',averagedata=True,xaxis='UVdist',coloraxis='field',plotfile='amp-vs-uvdist.png')
#
# figure 4
plotms(vis='3c391_ctm_mosaic_10s_spw0.ms',field='',correlation='RR,LL',timerange='',antenna='ea01',spw='0:31',xaxis='time',yaxis='antenna2',plotrange=[-1,-1,0,26],coloraxis='field',plotfile='3c391-datastream.png')
#
#
#
# calibrating the data
gencal(vis='3c391_ctm_mosaic_10s_spw0.ms',caltable='3c391_ctm_mosaic_10s_spw0.antpos',caltype='antpos')
setjy(vis='3c391_ctm_mosaic_10s_spw0.ms', listmodels=True)
setjy(vis='3c391_ctm_mosaic_10s_spw0.ms',field='J1331+3030',standard='Perley-Butler 2017',model='3C286_C.im',usescratch=True,scalebychan=True,spw='')
#
#
# Initial Phase Calibration
gaincal(vis='3c391_ctm_mosaic_10s_spw0.ms', caltable='3c391_ctm_mosaic_10s_spw0.G0all',field='0,1,9', refant='ea21', spw='0:27~36',gaintype='G',calmode='p', solint='int',minsnr=5, gaintable=['3c391_ctm_mosaic_10s_spw0.antpos'])
#
# figure 5
plotms(vis='3c391_ctm_mosaic_10s_spw0.G0all',xaxis='time',yaxis='phase',coloraxis='corr',iteraxis='antenna',plotrange=[-1,-1,-180,180],plotfile='3c391-polzn.png')
#
#
flagdata(vis='3c391_ctm_mosaic_10s_spw0.ms',flagbackup=True, mode='manual', antenna='ea05')
gaincal(vis='3c391_ctm_mosaic_10s_spw0.ms', caltable='3c391_ctm_mosaic_10s_spw0.G0',field='J1331+3030', refant='ea21', spw='0:27~36', calmode='p', solint='int',minsnr=5, gaintable=['3c391_ctm_mosaic_10s_spw0.antpos'])
#
# figure 5a
plotms(vis='3c391_ctm_mosaic_10s_spw0.G0',xaxis='time',yaxis='phase',coloraxis='corr',field='J1331+3030',iteraxis='antenna',plotrange=[-1,-1,-180,180],timerange='08:02:00~08:17:00',plotfile='3C286-G0all-phase-ea05.png')
#
# delay calibration
gaincal(vis='3c391_ctm_mosaic_10s_spw0.ms',caltable='3c391_ctm_mosaic_10s_spw0.K0',field='J1331+3030',refant='ea21',spw='0:5~58',gaintype='K',solint='inf',combine='scan',minsnr=5,gaintable=['3c391_ctm_mosaic_10s_spw0.antpos','3c391_ctm_mosaic_10s_spw0.G0'])
#
# figure 6
plotms(vis='3c391_ctm_mosaic_10s_spw0.K0',xaxis='antenna1',yaxis='delay',coloraxis='baseline',plotfile='3c391-K0-delay.png')
# 
# bandpass calibration
bandpass(vis='3c391_ctm_mosaic_10s_spw0.ms',caltable='3c391_ctm_mosaic_10s_spw0.B0',field='J1331+3030',spw='',refant='ea21',combine='scan',solint='inf',bandtype='B',gaintable=['3c391_ctm_mosaic_10s_spw0.antpos','3c391_ctm_mosaic_10s_spw0.G0','3c391_ctm_mosaic_10s_spw0.K0'])
#
# figure 8A amp
plotms(vis='3c391_ctm_mosaic_10s_spw0.B0',field='J1331+3030',xaxis='chan',yaxis='amp',coloraxis='corr',iteraxis='antenna',gridrows=2,gridcols=2,plotfile='3C286-B0-amp.png')
#
# figure 8B phase
plotms(vis='3c391_ctm_mosaic_10s_spw0.B0',field='J1331+3030',xaxis='chan',yaxis='phase',coloraxis='corr',plotrange=[-1,-1,-180,180],iteraxis='antenna',gridrows=2,gridcols=2,plotfile='3C286-B0-phase.png')
#
# gain calibration
gaincal(vis='3c391_ctm_mosaic_10s_spw0.ms',caltable='3c391_ctm_mosaic_10s_spw0.G1',field='J1331+3030',spw='0:5~58',solint='inf',refant='ea21',gaintype='G',calmode='ap',solnorm=False,gaintable=['3c391_ctm_mosaic_10s_spw0.antpos','3c391_ctm_mosaic_10s_spw0.K0','3c391_ctm_mosaic_10s_spw0.B0'],interp=['','','nearest'])
#
#
gaincal(vis='3c391_ctm_mosaic_10s_spw0.ms',caltable='3c391_ctm_mosaic_10s_spw0.G1',field='J1822-0938',spw='0:5~58',solint='inf',refant='ea21',gaintype='G',calmode='ap',gaintable=['3c391_ctm_mosaic_10s_spw0.antpos','3c391_ctm_mosaic_10s_spw0.K0','3c391_ctm_mosaic_10s_spw0.B0'],append=True)
#
# figure 9A gain phase solutions
plotms(vis='3c391_ctm_mosaic_10s_spw0.G1',xaxis='time',yaxis='phase',gridrows=1,gridcols=2,iteraxis='corr',coloraxis='baseline',plotrange=[-1,-1,-180,180],plotfile='plotms_3c391-G1-phase.png')
#
# figure 9B gain amplitude solutions
plotms(vis='3c391_ctm_mosaic_10s_spw0.G1',xaxis='time',yaxis='amp',gridrows=1,gridcols=2,iteraxis='corr',coloraxis='baseline',plotfile='plotms_3c391-G1-amp.png')
#
# figure 10
plotms(vis='3c391_ctm_mosaic_10s_spw0.G1', xaxis='time', yaxis='phase',correlation='/', coloraxis='baseline', plotrange=[-1,-1,-180,180],plotfile='3c391-G1-RLphasediff.png')
#
# scaling the amplitude gains
myscale = fluxscale(vis='3c391_ctm_mosaic_10s_spw0.ms',caltable='3c391_ctm_mosaic_10s_spw0.G1',fluxtable='3c391_ctm_mosaic_10s_spw0.fluxscale1',reference='J1331+3030',transfer=['J1822-0938'],incremental=False)
#
# figure 11A post fluxscale amplitude R
plotms(vis='3c391_ctm_mosaic_10s_spw0.fluxscale1',xaxis='time',yaxis='amp',correlation='R',coloraxis='baseline',plotfile='3c391-fluxscale1-amp-R.png')
#
# figure 11B post fluxscale amplitude L
plotms(vis='3c391_ctm_mosaic_10s_spw0.fluxscale1',xaxis='time',yaxis='amp',correlation='L',coloraxis='baseline',plotfile='3c391-fluxscale1-amp-L.png')
#
# applying the calibration
applycal(vis='3c391_ctm_mosaic_10s_spw0.ms',field='J1331+3030',gaintable=['3c391_ctm_mosaic_10s_spw0.antpos','3c391_ctm_mosaic_10s_spw0.fluxscale1','3c391_ctm_mosaic_10s_spw0.K0','3c391_ctm_mosaic_10s_spw0.B0'],gainfield=['','J1331+3030','',''],interp=['','nearest','',''],calwt=False)
#
#
applycal(vis='3c391_ctm_mosaic_10s_spw0.ms',field='J1822-0938',gaintable=['3c391_ctm_mosaic_10s_spw0.antpos','3c391_ctm_mosaic_10s_spw0.fluxscale1','3c391_ctm_mosaic_10s_spw0.K0','3c391_ctm_mosaic_10s_spw0.B0'],gainfield=['','J1822-0938','',''],interp=['','nearest','',''],calwt=False)
#
#
applycal(vis='3c391_ctm_mosaic_10s_spw0.ms',field='2~8',gaintable=['3c391_ctm_mosaic_10s_spw0.antpos','3c391_ctm_mosaic_10s_spw0.fluxscale1','3c391_ctm_mosaic_10s_spw0.K0','3c391_ctm_mosaic_10s_spw0.B0'],gainfield=['','J1822-0938','',''],interp=['','linear','',''],calwt=False)
#
# figure 12A amp vs channel 3C286
plotms(vis='3c391_ctm_mosaic_10s_spw0.ms',field='0',correlation='RR,LL',antenna='',avgtime='60',xaxis='channel',yaxis='amp',ydatacolumn='corrected',coloraxis='corr',plotfile='plotms_3c391-fld0-corrected-amp.png')
#
# figure 12B phase vs channel 3C286
plotms(vis='3c391_ctm_mosaic_10s_spw0.ms',field='0',correlation='RR,LL',antenna='',avgtime='60',xaxis='channel',yaxis='phase',ydatacolumn='corrected',coloraxis='corr',plotrange=[-1,-1,-180,180],plotfile='plotms_3c391-fld0-corrected-phase.png')
#
# figure 12C amp vs channel J1822-0938
plotms(vis='3c391_ctm_mosaic_10s_spw0.ms',field='1',correlation='RR,LL',antenna='',avgtime='60',xaxis='channel',yaxis='amp',ydatacolumn='corrected',coloraxis='corr',plotfile='plotms_3c391-fld1-corrected-amp.png')
#
# figure 12D phase vs channel J1822-0938
plotms(vis='3c391_ctm_mosaic_10s_spw0.ms',field='1',correlation='RR,LL',antenna='',avgtime='60',xaxis='channel',yaxis='phase',ydatacolumn='corrected',coloraxis='corr',plotrange=[-1,-1,-180,180],plotfile='plotms_3c391-fld1-corrected-phase.png')
#
#
split(vis='3c391_ctm_mosaic_10s_spw0.ms',outputvis='3c391_ctm_mosaic_spw0.ms',datacolumn='corrected',field='2~8',correlation='RR,LL')
#
#
statwt(vis='3c391_ctm_mosaic_spw0.ms',datacolumn='data')
#
#
# imaging parameters
#
# figure 13
plotms(vis='3c391_ctm_mosaic_spw0.ms',xaxis='uvwave',yaxis='amp',ydatacolumn='data',field='0',avgtime='30',correlation='RR',plotfile='plotms_3c391-mosaic0-uvwave.png',overwrite=True)
#
#
# multi scale mosaic clean
# tclean
tclean(vis='3c391_ctm_mosaic_spw0.ms',imagename='3c391_ctm_spw0_multiscale',field='',spw='',specmode='mfs',niter=20000,gain=0.1, threshold='1.0mJy',gridder='mosaic',deconvolver='multiscale',scales=[0, 5, 15, 45], smallscalebias=0.9,interactive=False,imsize=[480,480], cell=['2.5arcsec','2.5arcsec'],stokes='I',weighting='briggs',robust=0.5,pbcor=False,savemodel='modelcolumn',mask='tclean-1.mask')
#
#
impbcor(imagename='3c391_ctm_spw0_multiscale.image',pbimage='3c391_ctm_spw0_multiscale.pb',outfile='3c391_ctm_spw0_multiscale.pbcorimage')
# image anapysis
#
#
mystat = imstat(imagename='3c391_ctm_spw0_multiscale.pbcorimage')
#
#
# selfcal
#
delmod('3c391_ctm_mosaic_spw0.ms')
tclean(vis='3c391_ctm_mosaic_spw0.ms',imagename='3c391_ctm_spw0_ms_I',field='',spw='',specmode='mfs',niter=500,gain=0.1,threshold='1mJy',gridder='mosaic',deconvolver='multiscale',scales=[0, 5, 15, 45],smallscalebias=0.9,interactive=False,imsize=[480,480],cell=['2.5arcsec','2.5arcsec'],stokes='I',weighting='briggs',robust=0.5,pbcor=False,savemodel='modelcolumn',mask='tclean-1.mask')
#
#
#
gaincal(vis='3c391_ctm_mosaic_spw0.ms',caltable='3c391_ctm_mosaic_spw0.selfcal1',field='',spw='',selectdata=False,solint='30s',refant='ea21',minblperant=4,minsnr=3,gaintype='G',calmode='p')
#
applycal(vis='3c391_ctm_mosaic_spw0.ms',field='',spw='',selectdata=False,gaintable= ['3c391_ctm_mosaic_spw0.selfcal1'],gainfield=[''],interp=['nearest'],calwt=[False],applymode='calflag')
#
#
tclean(vis='3c391_ctm_mosaic_spw0.ms',imagename='3c391_ctm_spw0_multiscale_selfcal1',field='',spw='',specmode='mfs',niter=20000,gain=0.1,threshold='1mJy',gridder='mosaic',deconvolver='multiscale',scales=[0, 5, 15, 45],smallscalebias=0.9,interactive=False,imsize=[480,480],cell=['2.5arcsec','2.5arcsec'],stokes='I',weighting='briggs',robust=0.5,pbcor=False,savemodel='modelcolumn',mask='tclean-1.mask')
